server:
  port: 8081
spring:
  application:
    name: grade-provider
    main:
      allow-bean-definition-overriding: true
  logging:
    level:
      root: info
      org.springframework: info
  profiles:
    active: '@profiles.active@'
  datasource:
    url: jdbc:mysql://localhost:3306/grade?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
mybatis:
  type-aliases-package: cn.grade.service.entity
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka